import React, { useState, useEffect } from "react";
import "../../node_modules/bootstrap/dist/css/bootstrap.min.css";
import Head from "next/head";
import Header from "../inc/Header";

const SimpleAnime = ({ anime }: any) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <div className="card-single" style={{ width: "80%", margin: "auto" }}>
          <a href={anime.link}>
            <img
              src={`http://localhost:9999/assets/${anime.image}`}
              className="card-img-top"
              alt="..."
            />
          </a>
          <div className="card-body">
            <h5 className="card-title">{anime.name}</h5>
            <p className="card-text">{anime.date}</p>
            <p className="card-text">{anime.rate} *</p>
            <p className="card-text">{anime.description}</p>
          </div>
        </div>
      </main>
    </div>
  );
};

export async function getStaticProps({ params }: any) {
  const res = await fetch("http://localhost:9999/items/anime/" + params.id);
  const anime = (await res.json()).data;

  return {
    props: {
      anime,
    },
  };
}

export async function getStaticPaths() {
  const res = await fetch(`http://localhost:9999/items/anime`);
  const resAnime = (await res.json()).data;

  return {
    paths: resAnime.map((anime: any) => ({
      params: { id: anime.id.toString() },
    })),
    fallback: false,
  };
}

export default SimpleAnime;
