import "../node_modules/bootstrap/dist/css/bootstrap.min.css";
import Head from "next/head";
import Header from "./inc/Header";

export default function Home({ anime, totalAnimeCount }: any) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main>
        <div className="anime-card">
          {anime.data.map((manga: any) => (
            <div key={manga.id} className="card" style={{ width: "18rem" }}>
              <a href={manga.link}>
                <img
                  src={`http://localhost:9999/assets/${manga.image}`}
                  className="card-img-top"
                  alt="..."
                />
              </a>
              <div className="card-body">
                <h5 className="card-title">{manga.name}</h5>
                <p className="card-text">{manga.date}</p>
                <p className="card-text">{manga.rate} *</p>
                <p className="card-text">{manga.description}</p>
                <a
                  href={`http://localhost:3000/anime/${manga.id}`}
                  className="btn btn-primary"
                >
                  Watch
                </a>
              </div>
            </div>
          ))}
        </div>
        <nav aria-label="Page navigation example" style={{ margin: "auto" }}>
          <ul className="pagination">
            <li className="page-item">
              <a className="page-link" href="#" id="prev-btn">
                Previous
              </a>
            </li>
            <li className="page-item" id="pagination-number">
              <a className="page-link" href="#">
                1
              </a>
            </li>
            <li className="page-item">
              <a className="page-link" href="#" id="next-btn">
                Next
              </a>
            </li>
          </ul>
        </nav>
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const res = await fetch("http://localhost:9999/items/anime");
  const anime = await res.json();

  let totalAnimeCount = anime.data.length;

  return {
    props: {
      anime,
      totalAnimeCount,
    },
  };
}
